FILE_DATASET_NAME: TFM_Dataset.csv
RANDOM_SEED: 42
MAX_DATA_LEN: 200
BATCH_SIZE: 16
EPOCHS: 3
NUM_TYPES_CLASSIFICATION_CLASSES: 2
DATALOADER_NUM_WORKERS: 1
TRANSFER_LEARNING: True
DROP_OUT_BERT: 0.3
PRE_TRAINED_MODEL_NAME:
  BERT: bert-base-cased
  AlBERT: albert-base-v2
  RoBERTa: roberta-base